In [2]:
# ==========================================
# PROJECT 2 - ROAD ACCIDENT HOTSPOT INTELLIGENCE
# Stage 1: Data Loading & Initial Inspection
# ==========================================

import pandas as pd
import numpy as np

# ------------------------------------------
# 1. Load datasets
# ------------------------------------------

road_classification = pd.read_csv(
    "NCRB_ADSI_2023_Table_1A.7_2.csv"
)

time_occurrence = pd.read_csv(
    "NCRB_ADSI_2023_Table_1A.6_Road_Accidents_Time_of_Occurrence.csv"
)


# ------------------------------------------
# 2. Check dataset shapes
# ------------------------------------------

print("ROAD CLASSIFICATION DATASET")
print("Shape:", road_classification.shape)

print("\nTIME OF OCCURRENCE DATASET")
print("Shape:", time_occurrence.shape)


# ------------------------------------------
# 3. Display column names
# ------------------------------------------

print("\nROAD CLASSIFICATION COLUMNS")
print(road_classification.columns.tolist())

print("\nTIME OF OCCURRENCE COLUMNS")
print(time_occurrence.columns.tolist())


# ------------------------------------------
# 4. Display first 5 rows
# ------------------------------------------

print("\nROAD CLASSIFICATION - FIRST 5 ROWS")
display(road_classification.head())

print("\nTIME OF OCCURRENCE - FIRST 5 ROWS")
display(time_occurrence.head())


# ------------------------------------------
# 5. Display last 5 rows
# ------------------------------------------

print("\nROAD CLASSIFICATION - LAST 5 ROWS")
display(road_classification.tail())

print("\nTIME OF OCCURRENCE - LAST 5 ROWS")
display(time_occurrence.tail())

ROAD CLASSIFICATION DATASET
Shape: (93, 17)

TIME OF OCCURRENCE DATASET
Shape: (89, 11)

ROAD CLASSIFICATION COLUMNS
['Sl. No.', 'State/UT', 'National Highways - Cases', 'National Highways - Injured', 'National Highways - Died', 'State Highways - Cases', 'State Highways - Injured', 'State Highways - Died', 'Expressways - Cases', 'Expressways - Injured', 'Expressways - Died', 'Other Roads - Cases', 'Other Roads - Injured', 'Other Roads - Died', 'Total - Cases', 'Total - Injured', 'Total - Died']

TIME OF OCCURRENCE COLUMNS
['Geography Type', 'Geography', '0000-0300 (Night)', '0300-0600 (Night)', '0600-0900 (Day)', '0900-1200 (Day)', '1200-1500 (Day)', '1500-1800 (Day)', '1800-2100 (Night)', '2100-2400 (Night)', 'Total']

ROAD CLASSIFICATION - FIRST 5 ROWS

,Sl. No.,State/UT,National Highways - Cases,National Highways - Injured,National Highways - Died,State Highways - Cases,State Highways - Injured,State Highways - Died,Expressways - Cases,Expressways - Injured,Expressways - Died,Other Roads - Cases,Other Roads - Injured,Other Roads - Died,Total - Cases,Total - Injured,Total - Died
0,1,Andhra Pradesh,8276,8507,3806,4499,4595,1887,0,0,0,7174,7307,2444,19949,20409,8137
1,2,Arunachal Pradesh,146,150,75,23,16,17,0,0,0,64,52,44,233,218,136
2,3,Assam,3427,2770,1564,1750,1454,707,0,0,0,2244,1693,1025,7421,5917,3296
3,4,Bihar,4925,2925,4056,2264,1409,1805,0,0,0,3825,2205,3012,11014,6539,8873
4,5,Chhattisgarh,4024,3494,1921,2083,1855,1066,0,0,0,7362,6375,3179,13469,11724,6166

TIME OF OCCURRENCE - FIRST 5 ROWS

,Geography Type,Geography,0000-0300 (Night),0300-0600 (Night),0600-0900 (Day),0900-1200 (Day),1200-1500 (Day),1500-1800 (Day),1800-2100 (Night),2100-2400 (Night),Total
0,State/UT,ANDHRA PRADESH,991,1143,2256,2704,3058,3403,4255,2139,19949
1,State/UT,ARUNACHAL PRADESH,18,13,23,22,36,55,46,20,233
2,State/UT,ASSAM,346,389,889,1025,1051,1327,1294,1100,7421
3,State/UT,BIHAR,701,937,1674,1606,1525,1818,1803,950,11014
4,State/UT,CHHATTISGARH,464,406,1067,1990,2211,2534,3279,1518,13469

ROAD CLASSIFICATION - LAST 5 ROWS

,Sl. No.,State/UT,National Highways - Cases,National Highways - Injured,National Highways - Died,State Highways - Cases,State Highways - Injured,State Highways - Died,Expressways - Cases,Expressways - Injured,Expressways - Died,Other Roads - Cases,Other Roads - Injured,Other Roads - Died,Total - Cases,Total - Injured,Total - Died
88,86,Varanasi,89,79,96,49,56,36,0,0,0,58,23,91,196,158,223
89,87,Vasai Virar,112,45,82,25,12,14,0,0,0,228,189,58,365,246,154
90,88,Vijayawada,675,584,198,165,161,55,0,0,0,682,671,120,1522,1416,373
91,89,Vishakhapatnam,477,440,132,41,35,9,0,0,0,775,747,181,1293,1222,322
92,Total (Cities),Total (Cities),13882,12346,4258,8587,7733,1966,775,455,469,46666,43247,9487,69910,63781,16180

TIME OF OCCURRENCE - LAST 5 ROWS

,Geography Type,Geography,0000-0300 (Night),0300-0600 (Night),0600-0900 (Day),0900-1200 (Day),1200-1500 (Day),1500-1800 (Day),1800-2100 (Night),2100-2400 (Night),Total
84,City,VARANASI,21,25,27,23,27,23,23,27,196
85,City,VASAI VIRAR,30,24,45,53,58,36,66,53,365
86,City,VIJAYAWADA,86,74,159,218,236,228,295,226,1522
87,City,VISHAKHAPATNAM,61,56,179,190,194,216,245,152,1293
88,City,NAGPUR,93,40,109,195,195,160,202,219,1213

In [3]:
# ==========================================
# PROJECT 2 - ROAD ACCIDENT HOTSPOT INTELLIGENCE
# Stage 2: Data Quality Check
# ==========================================

# ------------------------------------------
# 1. Check data types
# ------------------------------------------

print("ROAD CLASSIFICATION - DATA TYPES")
print(road_classification.dtypes)

print("\nTIME OF OCCURRENCE - DATA TYPES")
print(time_occurrence.dtypes)


# ------------------------------------------
# 2. Check missing values
# ------------------------------------------

print("\nROAD CLASSIFICATION - MISSING VALUES")
print(road_classification.isnull().sum())

print("\nTIME OF OCCURRENCE - MISSING VALUES")
print(time_occurrence.isnull().sum())


# ------------------------------------------
# 3. Check duplicate rows
# ------------------------------------------

print("\nROAD CLASSIFICATION - DUPLICATE ROWS")
print(road_classification.duplicated().sum())

print("\nTIME OF OCCURRENCE - DUPLICATE ROWS")
print(time_occurrence.duplicated().sum())


# ------------------------------------------
# 4. Check unique geography types
# ------------------------------------------

print("\nTIME OF OCCURRENCE - GEOGRAPHY TYPES")
print(time_occurrence["Geography Type"].value_counts())


# ------------------------------------------
# 5. Check aggregate / total rows
# ------------------------------------------

print("\nROAD CLASSIFICATION - TOTAL / AGGREGATE ROWS")

display(
    road_classification[
        road_classification["State/UT"]
        .astype(str)
        .str.contains("TOTAL", case=False, na=False)
    ]
)


print("\nTIME OF OCCURRENCE - TOTAL / AGGREGATE ROWS")

display(
    time_occurrence[
        time_occurrence["Geography"]
        .astype(str)
        .str.contains("TOTAL", case=False, na=False)
    ]
)


# ------------------------------------------
# 6. Check numerical summary
# ------------------------------------------

print("\nROAD CLASSIFICATION - NUMERICAL SUMMARY")
display(road_classification.describe())


print("\nTIME OF OCCURRENCE - NUMERICAL SUMMARY")
display(time_occurrence.describe())

ROAD CLASSIFICATION - DATA TYPES
Sl. No.                          str
State/UT                         str
National Highways - Cases      int64
National Highways - Injured    int64
National Highways - Died       int64
State Highways - Cases         int64
State Highways - Injured       int64
State Highways - Died          int64
Expressways - Cases            int64
Expressways - Injured          int64
Expressways - Died             int64
Other Roads - Cases            int64
Other Roads - Injured          int64
Other Roads - Died             int64
Total - Cases                  int64
Total - Injured                int64
Total - Died                   int64
dtype: object

TIME OF OCCURRENCE - DATA TYPES
Geography Type         str
Geography              str
0000-0300 (Night)    int64
0300-0600 (Night)    int64
0600-0900 (Day)      int64
0900-1200 (Day)      int64
1200-1500 (Day)      int64
1500-1800 (Day)      int64
1800-2100 (Night)    int64
2100-2400 (Night)    int64
Total                int64
dtype: object

ROAD CLASSIFICATION - MISSING VALUES
Sl. No.                        0
State/UT                       0
National Highways - Cases      0
National Highways - Injured    0
National Highways - Died       0
State Highways - Cases         0
State Highways - Injured       0
State Highways - Died          0
Expressways - Cases            0
Expressways - Injured          0
Expressways - Died             0
Other Roads - Cases            0
Other Roads - Injured          0
Other Roads - Died             0
Total - Cases                  0
Total - Injured                0
Total - Died                   0
dtype: int64

TIME OF OCCURRENCE - MISSING VALUES
Geography Type       0
Geography            0
0000-0300 (Night)    0
0300-0600 (Night)    0
0600-0900 (Day)      0
0900-1200 (Day)      0
1200-1500 (Day)      0
1500-1800 (Day)      0
1800-2100 (Night)    0
2100-2400 (Night)    0
Total                0
dtype: int64

ROAD CLASSIFICATION - DUPLICATE ROWS
0

TIME OF OCCURRENCE - DUPLICATE ROWS
0

TIME OF OCCURRENCE - GEOGRAPHY TYPES
Geography Type
City        53
State/UT    36
Name: count, dtype: int64

ROAD CLASSIFICATION - TOTAL / AGGREGATE ROWS

,Sl. No.,State/UT,National Highways - Cases,National Highways - Injured,National Highways - Died,State Highways - Cases,State Highways - Injured,State Highways - Died,Expressways - Cases,Expressways - Injured,Expressways - Died,Other Roads - Cases,Other Roads - Injured,Other Roads - Died,Total - Cases,Total - Injured,Total - Died
28,Total (States),Total (States),137048,131656,59357,105048,104751,40343,3617,2758,2363,204313,193221,69026,450026,432386,171089
37,Total (UTs),Total (UTs),3702,4537,770,1428,1565,268,13,4,9,8860,9477,1690,14003,15583,2737
38,Total (All India),Total (All India),140750,136193,60127,106476,106316,40611,3630,2762,2372,213173,202698,70716,464029,447969,173826
92,Total (Cities),Total (Cities),13882,12346,4258,8587,7733,1966,775,455,469,46666,43247,9487,69910,63781,16180

TIME OF OCCURRENCE - TOTAL / AGGREGATE ROWS

Empty DataFrame
Columns: [Geography Type, Geography, 0000-0300 (Night), 0300-0600 (Night), 0600-0900 (Day), 0900-1200 (Day), 1200-1500 (Day), 1500-1800 (Day), 1800-2100 (Night), 2100-2400 (Night), Total]
Index: []

ROAD CLASSIFICATION - NUMERICAL SUMMARY

,National Highways - Cases,National Highways - Injured,National Highways - Died,State Highways - Cases,State Highways - Injured,State Highways - Died,Expressways - Cases,Expressways - Injured,Expressways - Died,Other Roads - Cases,Other Roads - Injured,Other Roads - Died,Total - Cases,Total - Injured,Total - Died
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.00000,93.000000,93.000000,93.000000,93.000000,93.000000
mean,4838.860215,4658.827957,2031.150538,3619.376344,3595.849462,1352.311828,133.763441,98.881720,86.602151,7880.11828,7468.688172,2485.182796,16472.118280,15822.247312,5955.247312
std,20335.316925,19667.333081,8730.275215,15598.534032,15616.065658,5942.239030,574.383742,434.687915,382.598187,30794.26405,29259.708228,10229.636066,67121.849696,64802.511034,25233.517960
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,98.000000,64.000000,38.000000,35.000000,27.000000,13.000000,0.000000,0.000000,0.000000,248.00000,166.000000,65.000000,476.000000,380.000000,158.000000
50%,302.000000,317.000000,90.000000,132.000000,140.000000,37.000000,0.000000,0.000000,0.000000,591.00000,627.000000,168.000000,1293.000000,1194.000000,305.000000
75%,1152.000000,1212.000000,416.000000,729.000000,690.000000,222.000000,13.000000,3.000000,4.000000,3241.00000,2205.000000,1025.000000,5715.000000,4162.000000,1457.000000
max,140750.000000,136193.000000,60127.000000,106476.000000,106316.000000,40611.000000,3630.000000,2762.000000,2372.000000,213173.00000,202698.000000,70716.000000,464029.000000,447969.000000,173826.000000

TIME OF OCCURRENCE - NUMERICAL SUMMARY

,0000-0300 (Night),0300-0600 (Night),0600-0900 (Day),0900-1200 (Day),1200-1500 (Day),1500-1800 (Day),1800-2100 (Night),2100-2400 (Night),Total
count,89.000000,89.000000,89.000000,89.000000,89.000000,89.000000,89.000000,89.000000,89.000000
mean,335.415730,337.651685,628.033708,853.617978,896.921348,1027.539326,1213.820225,706.314607,5999.314607
std,660.461543,685.208563,1293.205052,1782.492194,1882.241086,2201.016067,2731.671015,1410.457249,12428.069695
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,26.000000,21.000000,40.000000,60.000000,64.000000,65.000000,66.000000,62.000000,472.000000
50%,61.000000,53.000000,124.000000,179.000000,190.000000,176.000000,203.000000,177.000000,1213.000000
75%,291.000000,252.000000,400.000000,586.000000,621.000000,647.000000,658.000000,501.000000,3653.000000
max,3592.000000,3767.000000,7535.000000,9629.000000,9770.000000,11723.000000,17159.000000,6905.000000,67213.000000

In [4]:
# ==========================================
# Stage 3: Data Consistency Validation
# ==========================================

# ------------------------------------------
# 1. Validate Road Classification totals
# ------------------------------------------

road_classification["Calculated Cases"] = (
    road_classification["National Highways - Cases"]
    + road_classification["State Highways - Cases"]
    + road_classification["Expressways - Cases"]
    + road_classification["Other Roads - Cases"]
)

road_classification["Calculated Injured"] = (
    road_classification["National Highways - Injured"]
    + road_classification["State Highways - Injured"]
    + road_classification["Expressways - Injured"]
    + road_classification["Other Roads - Injured"]
)

road_classification["Calculated Died"] = (
    road_classification["National Highways - Died"]
    + road_classification["State Highways - Died"]
    + road_classification["Expressways - Died"]
    + road_classification["Other Roads - Died"]
)


# ------------------------------------------
# 2. Compare calculated totals with reported
# ------------------------------------------

print("CASES TOTAL MATCH:")
print(
    (road_classification["Calculated Cases"]
     == road_classification["Total - Cases"]).all()
)

print("\nINJURED TOTAL MATCH:")
print(
    (road_classification["Calculated Injured"]
     == road_classification["Total - Injured"]).all()
)

print("\nDIED TOTAL MATCH:")
print(
    (road_classification["Calculated Died"]
     == road_classification["Total - Died"]).all()
)


# ------------------------------------------
# 3. Show any mismatches
# ------------------------------------------

print("\nCASE TOTAL MISMATCHES")
display(
    road_classification[
        road_classification["Calculated Cases"]
        != road_classification["Total - Cases"]
    ]
)

print("\nINJURED TOTAL MISMATCHES")
display(
    road_classification[
        road_classification["Calculated Injured"]
        != road_classification["Total - Injured"]
    ]
)

print("\nDEATH TOTAL MISMATCHES")
display(
    road_classification[
        road_classification["Calculated Died"]
        != road_classification["Total - Died"]
    ]
)


# ------------------------------------------
# 4. Validate Time of Occurrence totals
# ------------------------------------------

time_columns = [
    "0000-0300 (Night)",
    "0300-0600 (Night)",
    "0600-0900 (Day)",
    "0900-1200 (Day)",
    "1200-1500 (Day)",
    "1500-1800 (Day)",
    "1800-2100 (Night)",
    "2100-2400 (Night)"
]

time_occurrence["Calculated Total"] = (
    time_occurrence[time_columns].sum(axis=1)
)


print("\nTIME OF OCCURRENCE TOTAL MATCH:")
print(
    (time_occurrence["Calculated Total"]
     == time_occurrence["Total"]).all()
)


# ------------------------------------------
# 5. Show any time-total mismatches
# ------------------------------------------

print("\nTIME TOTAL MISMATCHES")

display(
    time_occurrence[
        time_occurrence["Calculated Total"]
        != time_occurrence["Total"]
    ]
)

CASES TOTAL MATCH:
True

INJURED TOTAL MATCH:
True

DIED TOTAL MATCH:
True

CASE TOTAL MISMATCHES

Empty DataFrame
Columns: [Sl. No., State/UT, National Highways - Cases, National Highways - Injured, National Highways - Died, State Highways - Cases, State Highways - Injured, State Highways - Died, Expressways - Cases, Expressways - Injured, Expressways - Died, Other Roads - Cases, Other Roads - Injured, Other Roads - Died, Total - Cases, Total - Injured, Total - Died, Calculated Cases, Calculated Injured, Calculated Died]
Index: []

INJURED TOTAL MISMATCHES

Empty DataFrame
Columns: [Sl. No., State/UT, National Highways - Cases, National Highways - Injured, National Highways - Died, State Highways - Cases, State Highways - Injured, State Highways - Died, Expressways - Cases, Expressways - Injured, Expressways - Died, Other Roads - Cases, Other Roads - Injured, Other Roads - Died, Total - Cases, Total - Injured, Total - Died, Calculated Cases, Calculated Injured, Calculated Died]
Index: []

DEATH TOTAL MISMATCHES

Empty DataFrame
Columns: [Sl. No., State/UT, National Highways - Cases, National Highways - Injured, National Highways - Died, State Highways - Cases, State Highways - Injured, State Highways - Died, Expressways - Cases, Expressways - Injured, Expressways - Died, Other Roads - Cases, Other Roads - Injured, Other Roads - Died, Total - Cases, Total - Injured, Total - Died, Calculated Cases, Calculated Injured, Calculated Died]
Index: []

TIME OF OCCURRENCE TOTAL MATCH:
True

TIME TOTAL MISMATCHES

Empty DataFrame
Columns: [Geography Type, Geography, 0000-0300 (Night), 0300-0600 (Night), 0600-0900 (Day), 0900-1200 (Day), 1200-1500 (Day), 1500-1800 (Day), 1800-2100 (Night), 2100-2400 (Night), Total, Calculated Total]
Index: []

In [5]:
# ==========================================
# PROJECT 2 - ROAD ACCIDENT HOTSPOT INTELLIGENCE
# Stage 4: Data Cleaning
# ==========================================

# ------------------------------------------
# 1. Remove aggregate rows from
#    Road Classification dataset
# ------------------------------------------

road_classification = road_classification[
    ~road_classification["State/UT"]
    .astype(str)
    .str.contains("Total", case=False, na=False)
].copy()


# ------------------------------------------
# 2. Remove temporary validation columns
# ------------------------------------------

road_classification = road_classification.drop(
    columns=[
        "Calculated Cases",
        "Calculated Injured",
        "Calculated Died"
    ]
)


# ------------------------------------------
# 3. Remove aggregate rows from
#    Time of Occurrence dataset
# ------------------------------------------

time_occurrence = time_occurrence[
    ~time_occurrence["Geography"]
    .astype(str)
    .str.contains("Total", case=False, na=False)
].copy()


# ------------------------------------------
# 4. Remove temporary validation column
# ------------------------------------------

time_occurrence = time_occurrence.drop(
    columns=["Calculated Total"]
)


# ------------------------------------------
# 5. Reset indexes
# ------------------------------------------

road_classification.reset_index(drop=True, inplace=True)
time_occurrence.reset_index(drop=True, inplace=True)


# ------------------------------------------
# 6. Check cleaned shapes
# ------------------------------------------

print("ROAD CLASSIFICATION - CLEANED SHAPE:")
print(road_classification.shape)

print("\nTIME OF OCCURRENCE - CLEANED SHAPE:")
print(time_occurrence.shape)


# ------------------------------------------
# 7. Verify no aggregate rows remain
# ------------------------------------------

print("\nROAD CLASSIFICATION - TOTAL ROWS REMAINING:")
print(
    road_classification["State/UT"]
    .astype(str)
    .str.contains("Total", case=False, na=False)
    .sum()
)

print("\nTIME OF OCCURRENCE - TOTAL ROWS REMAINING:")
print(
    time_occurrence["Geography"]
    .astype(str)
    .str.contains("Total", case=False, na=False)
    .sum()
)


# ------------------------------------------
# 8. Final missing-value check
# ------------------------------------------

print("\nROAD CLASSIFICATION - TOTAL MISSING VALUES:")
print(road_classification.isnull().sum().sum())

print("\nTIME OF OCCURRENCE - TOTAL MISSING VALUES:")
print(time_occurrence.isnull().sum().sum())


# ------------------------------------------
# 9. Final duplicate check
# ------------------------------------------

print("\nROAD CLASSIFICATION - DUPLICATES:")
print(road_classification.duplicated().sum())

print("\nTIME OF OCCURRENCE - DUPLICATES:")
print(time_occurrence.duplicated().sum())

ROAD CLASSIFICATION - CLEANED SHAPE:
(89, 17)

TIME OF OCCURRENCE - CLEANED SHAPE:
(89, 11)

ROAD CLASSIFICATION - TOTAL ROWS REMAINING:
0

TIME OF OCCURRENCE - TOTAL ROWS REMAINING:
0

ROAD CLASSIFICATION - TOTAL MISSING VALUES:
0

TIME OF OCCURRENCE - TOTAL MISSING VALUES:
0

ROAD CLASSIFICATION - DUPLICATES:
0

TIME OF OCCURRENCE - DUPLICATES:
0

In [6]:
# ==========================================
# PROJECT 2 - ROAD ACCIDENT HOTSPOT INTELLIGENCE
# Stage 5: Feature Engineering
# ==========================================


# ==================================================
# PART A: ROAD CLASSIFICATION DATASET
# ==================================================

# ------------------------------------------
# 1. Accident Share (%)
# ------------------------------------------

road_classification["Accident Share (%)"] = (
    road_classification["Total - Cases"]
    / road_classification["Total - Cases"].sum()
) * 100


# ------------------------------------------
# 2. Injury Rate (%)
# ------------------------------------------

road_classification["Injury Rate (%)"] = (
    road_classification["Total - Injured"]
    / road_classification["Total - Cases"]
) * 100


# ------------------------------------------
# 3. Fatality Rate (%)
# ------------------------------------------

road_classification["Fatality Rate (%)"] = (
    road_classification["Total - Died"]
    / road_classification["Total - Cases"]
) * 100


# ==================================================
# PART B: TIME OF OCCURRENCE DATASET
# ==================================================

# ------------------------------------------
# 4. Create Day Accident Total
# ------------------------------------------

day_columns = [
    "0600-0900 (Day)",
    "0900-1200 (Day)",
    "1200-1500 (Day)",
    "1500-1800 (Day)"
]

time_occurrence["Day Accidents"] = (
    time_occurrence[day_columns].sum(axis=1)
)


# ------------------------------------------
# 5. Create Night Accident Total
# ------------------------------------------

night_columns = [
    "0000-0300 (Night)",
    "0300-0600 (Night)",
    "1800-2100 (Night)",
    "2100-2400 (Night)"
]

time_occurrence["Night Accidents"] = (
    time_occurrence[night_columns].sum(axis=1)
)


# ------------------------------------------
# 6. Day Accident Share (%)
# ------------------------------------------

time_occurrence["Day Accident Share (%)"] = (
    time_occurrence["Day Accidents"]
    / time_occurrence["Total"]
) * 100


# ------------------------------------------
# 7. Night Accident Share (%)
# ------------------------------------------

time_occurrence["Night Accident Share (%)"] = (
    time_occurrence["Night Accidents"]
    / time_occurrence["Total"]
) * 100


# ------------------------------------------
# 8. Identify Peak Time Period
# ------------------------------------------

time_occurrence["Peak Time Period"] = (
    time_occurrence[time_columns]
    .idxmax(axis=1)
)


# ------------------------------------------
# 9. Get Peak Time Accident Count
# ------------------------------------------

time_occurrence["Peak Time Accidents"] = (
    time_occurrence[time_columns]
    .max(axis=1)
)


# ==================================================
# PART C: CHECK THE NEW FEATURES
# ==================================================

print("ROAD CLASSIFICATION - NEW FEATURES")

display(
    road_classification[
        [
            "State/UT",
            "Total - Cases",
            "Total - Injured",
            "Total - Died",
            "Accident Share (%)",
            "Injury Rate (%)",
            "Fatality Rate (%)"
        ]
    ].head()
)


print("\nTIME OF OCCURRENCE - NEW FEATURES")

display(
    time_occurrence[
        [
            "Geography Type",
            "Geography",
            "Day Accidents",
            "Night Accidents",
            "Day Accident Share (%)",
            "Night Accident Share (%)",
            "Peak Time Period",
            "Peak Time Accidents"
        ]
    ].head()
)


# ==================================================
# PART D: VALIDATE FEATURE ENGINEERING
# ==================================================

print("\nDAY + NIGHT ACCIDENTS SHOULD EQUAL TOTAL")

print(
    (
        time_occurrence["Day Accidents"]
        + time_occurrence["Night Accidents"]
        == time_occurrence["Total"]
    ).all()
)

ROAD CLASSIFICATION - NEW FEATURES

,State/UT,Total - Cases,Total - Injured,Total - Died,Accident Share (%),Injury Rate (%),Fatality Rate (%)
0,Andhra Pradesh,19949,20409,8137,3.736195,102.305880,40.789012
1,Arunachal Pradesh,233,218,136,0.043638,93.562232,58.369099
2,Assam,7421,5917,3296,1.389859,79.733190,44.414499
3,Bihar,11014,6539,8873,2.062782,59.369893,80.561104
4,Chhattisgarh,13469,11724,6166,2.522573,87.044324,45.779197

TIME OF OCCURRENCE - NEW FEATURES

,Geography Type,Geography,Day Accidents,Night Accidents,Day Accident Share (%),Night Accident Share (%),Peak Time Period,Peak Time Accidents
0,State/UT,ANDHRA PRADESH,11421,8528,57.250990,42.749010,1800-2100 (Night),4255
1,State/UT,ARUNACHAL PRADESH,136,97,58.369099,41.630901,1500-1800 (Day),55
2,State/UT,ASSAM,4292,3129,57.835871,42.164129,1500-1800 (Day),1327
3,State/UT,BIHAR,6623,4391,60.132559,39.867441,1500-1800 (Day),1818
4,State/UT,CHHATTISGARH,7802,5667,57.925607,42.074393,1800-2100 (Night),3279

DAY + NIGHT ACCIDENTS SHOULD EQUAL TOTAL
True

In [7]:
# ==========================================
# Stage 6: Export Cleaned Analytical Data
# ==========================================

road_classification.to_csv(
    "road_classification_cleaned.csv",
    index=False
)

time_occurrence.to_csv(
    "time_occurrence_cleaned.csv",
    index=False
)

print("Files exported successfully.")

print("\nRoad Classification:")
print(road_classification.shape)

print("\nTime of Occurrence:")
print(time_occurrence.shape)

Files exported successfully.

Road Classification:
(89, 20)

Time of Occurrence:
(89, 17)

In [ ]:
import os

print(os.path.abspath("road_classification_cleaned.csv"))
print(os.path.abspath("time_occurrence_cleaned.csv"))